deployment:
  tasks:
    - export COREPATH=/home/gosdevelopment/well-known
    - export PUBLICPATH=/home/gosdevelopment/public_html
    - /bin/mkdir -p $COREPATH
    - /bin/cp -R * $COREPATH
    - test -f $COREPATH/.env || /bin/cp .env.example $COREPATH/.env
    - /bin/grep -q "^APP_URL=" $COREPATH/.env || /bin/echo "APP_URL=https://go.sdevelopment.tech" >> $COREPATH/.env
    - /bin/grep -q "^APP_KEY=" $COREPATH/.env || /bin/echo "APP_KEY=base64:vvaJG2ZCgA+5DXKDMCNX8K//tUTydoWnW3c955cf3Qs=" >> $COREPATH/.env
    - /bin/grep -q "^JWT_SECRET=" $COREPATH/.env || /bin/echo "JWT_SECRET=11uO7YWOGcbHvaBTsMmzYqiZKa71UnZt6rZpN5bQPRboURhhMAUCcGAgMawgpw9m" >> $COREPATH/.env
    - /bin/cp -rf public/* $PUBLICPATH/
    - /bin/cp -f public/.htaccess $PUBLICPATH/
    - /bin/sed -i "s|__DIR__.'/../|__DIR__.'/../well-known/|g" $PUBLICPATH/index.php
    - export COMPOSER_HOME=/home/gosdevelopment/.composer
    - cd $COREPATH && composer install --optimize-autoloader --no-dev --ignore-platform-reqs
    - cd $COREPATH && php artisan migrate --force
    - cd $COREPATH && php artisan optimize:clear
