deployment:
  tasks:
    - export COREPATH=/home/gosdevelopment/well-known
    - export PUBLICPATH=/home/gosdevelopment/public_html
    - /bin/mkdir -p $COREPATH
    - /bin/cp -R * $COREPATH
    - /bin/cp .env.example $COREPATH/.env
    - /bin/sed -i "s/DB_DATABASE=.*/DB_DATABASE=gosdevelopment_main/" $COREPATH/.env
    - /bin/sed -i "s/DB_USERNAME=.*/DB_USERNAME=gosdevelopment_go/" $COREPATH/.env
    - /bin/sed -i "s/DB_PASSWORD=.*/DB_PASSWORD=\".N?~Gyh^T)7X!MNn\"/" $COREPATH/.env
    - /bin/sed -i "s/APP_URL=.*/APP_URL=https:\/\/go.sdevelopment.tech/" $COREPATH/.env
    - /bin/sed -i "s/APP_KEY=.*/APP_KEY=base64:vvaJG2ZCgA+5DXKDMCNX8K\/\/tUTydoWnW3c955cf3Qs=/" $COREPATH/.env
    - /bin/grep -q "^JWT_SECRET=" $COREPATH/.env || /bin/echo "JWT_SECRET=11uO7YWOGcbHvaBTsMmzYqiZKa71UnZt6rZpN5bQPRboURhhMAUCcGAgMawgpw9m" >> $COREPATH/.env
    - /bin/cp -rf public/* $PUBLICPATH/
    - /bin/cp -f public/.htaccess $PUBLICPATH/
    - /bin/sed -i "s|__DIR__.'/../|__DIR__.'/../well-known/|g" $PUBLICPATH/index.php
